### ISSUE TITLE
Generating Data

### ISSUE THREAD

**Issue by Freddy-2021** [learn-co-curriculum/dsc-generating-data#3]
### Canvas Link

https://flatiron.illumidesk.com/user/fred0421/notebooks/dsc-generating-data/index.ipynb

### Concern

under make_blobs(): 
the import sklearn.datasets.samples_generator  results in an error. It  works if you do the following:

# Import make_blobs
from sklearn.datasets import make_blobs

**Comment by hoffm386** [comment]
Thanks for flagging! The import has been fixed in the latest update https://github.com/learn-co-curriculum/dsc-generating-data/commit/fa16a739583c084333490e65ca65867d94ec9b1a
